vars:
  version: v1.0.0

templates:
  motd.j2: motd.j2

handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

tasks:
  - name: set motd banner
    template:
      src: "motd.j2"
      dest: "/etc/motd"
      mode: 0700
    notify: restart nginx
    tags: [ common, oranda ]

  - name: install nginx
    apt:
      name: nginx
      state: latest
    tags: [ common, oranda ]
